dev_directory: ../dev_data
eval_directory: ../eval_data
model_directory: ./model
result_directory: ./result
result_file: result.csv

max_fpr: 0.1

ast_embedding_size: 768

fit:
  lr: 0.00001
  epochs: 500
  batch_size: 32
  shuffle: True
  nbLayers: 1
  normalization: "layer"
  activation: "gelu"
  epsilon: 0.1
  validation_split: 0.1
  verbose: 1